apiVersion: apps/v1
kind: Deployment
metadata: 
  name: restapi-deployment
  namespace: my-api-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
      - name: restapi-container
        image: docker.io/ellieanna/restapi-docker:v1
        ports:
        - containerPort: 3333