apiVersion: v1
kind: Pod
metadata: 
  name: restapi-pod
  namespace: my-api-namespace
spec: 
  containers: 
  - name: restapi-container
    image: docker.io/ellieanna/restapi-docker:v1
    ports: 
    - containerPort: 3333